version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: rrhh-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saas_rrhh
    ports:
      - "3307:3306" # Expone en el 3307 para no chocar con tu XAMPP local
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: 
      context: ./backend/rrhh-backend
    container_name: rrhh-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/saas_rrhh?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: rrhh-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
